package sudokusudoku;

import javax.swing.JTextField;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.Scanner;

/**
 *
 * @author k_ell
 */

//(For test class) editable set to false
public class sudokuTest extends javax.swing.JFrame {
    SudokuBoard SB = new SudokuBoard();
    Scanner scan = new Scanner(System.in);
    

    JTextField selectedTextField;
    /**
     * Creates new form SudokuFrame
     */
    public sudokuTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()
    {

//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jButton3 = new javax.swing.JButton();
//        jButton4 = new javax.swing.JButton();
//        jButton5 = new javax.swing.JButton();
//        jButton6 = new javax.swing.JButton();
//        jButton7 = new javax.swing.JButton();
//        jButton8 = new javax.swing.JButton();
//        jButton9 = new javax.swing.JButton();
        setTitle("Sudoku");
        jButtonQuit = new javax.swing.JButton();
        jButtonBad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField00 = new javax.swing.JTextField();
        jTextField01 = new javax.swing.JTextField();
        jTextField02 = new javax.swing.JTextField();
        jTextField03 = new javax.swing.JTextField();
        jTextField04 = new javax.swing.JTextField();
        jTextField05 = new javax.swing.JTextField();
        jTextField06 = new javax.swing.JTextField();
        jTextField07 = new javax.swing.JTextField();
        jTextField08 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jTextField87 = new javax.swing.JTextField();
        jTextField88 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


        jButtonQuit.setText("I quit (new game)");

        jButtonBad.setText("I'm bad, HELP!");
        
//        jButton1.addFocusListener(new java.awt.event.FocusListener()
//        {
//            private void jButton1FocusGained(java.awt.event.FocusEvent evt)
//            {
//                selectedTextField = (JTextField) evt.getSource();
//            }
//
//            @Override
//            public void focusGained(FocusEvent evt) {
//                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                //selectedTextField = (JTextField) evt.getSource();
//                selectedTextField.setText(selectedTextField.getText() + "1");
//            }
//
//            @Override
//            public void focusLost(FocusEvent fe) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField00, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField01, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField02, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField03, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField04, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField05, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField06, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField07, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField08, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            
                           
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField83, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField85, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField86, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField87, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField88, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    //.addComponent(jButton9)
                    //.addComponent(jButton7)
                   // .addComponent(jButton5)
                   // .addComponent(jButton3)
                   // .addComponent(jButton1)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                )
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jButtonQuit)
                .addGap(28, 28, 28)
                .addComponent(jButtonBad)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           // .addComponent(jButton1)
                           // .addComponent(jButton2)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           // .addComponent(jButton3)
                            //.addComponent(jButton4)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           // .addComponent(jButton5)
                            //.addComponent(jButton6)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            //.addComponent(jButton7)
                            //.addComponent(jButton8)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        //.addComponent(jButton9)
                        ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuit)
                    .addComponent(jButtonBad))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        //jButton1.addActionListener(new ActionListener()
        {
            //           @Override
            //          public void actionPerformed(ActionEvent e)
            {
                //             jTextField00.setText(jButton1.getText());
                //         }
            //     });


    pack();
    }// </editor-fold>                        

            //method to generate a board and set the indexes to the textfields
            newBoard();
            
            jButtonQuit.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    newBoard();
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });
            jButtonBad.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    String empty = "";
                    if(jTextField01.getText().equals(empty)) {
                        jTextField01.setText(Integer.toString(SB.getIndex(0, 1)));
                        jTextField01.setEditable(false);
                    }
                    else if (jTextField02.getText().equals(empty)){
                        jTextField02.setText(Integer.toString(SB.getIndex(0, 2)));
                        jTextField02.setEditable(false);
                    }
                    else if (jTextField04.getText().equals(empty)){
                        jTextField04.setText(Integer.toString(SB.getIndex(0, 4)));
                        jTextField04.setEditable(false);
                    }
                    else if (jTextField07.getText().equals(empty)){
                        jTextField07.setText(Integer.toString(SB.getIndex(0, 7)));
                        jTextField07.setEditable(false);
                    }
                    else if (jTextField10.getText().equals(empty)){
                        jTextField10.setText(Integer.toString(SB.getIndex(1, 0)));
                        jTextField10.setEditable(false);
                    }
                    else if (jTextField12.getText().equals(empty)){
                        jTextField12.setText(Integer.toString(SB.getIndex(1, 2)));
                        jTextField12.setEditable(false);
                    }
                    else if (jTextField16.getText().equals(empty)){
                        jTextField16.setText(Integer.toString(SB.getIndex(1, 6)));
                        jTextField16.setEditable(false);
                    }
                    else if (jTextField20.getText().equals(empty)){
                        jTextField20.setText(Integer.toString(SB.getIndex(2, 0)));
                        jTextField20.setEditable(false);
                    }
                    else if (jTextField23.getText().equals(empty)){
                        jTextField23.setText(Integer.toString(SB.getIndex(2, 3)));
                        jTextField23.setEditable(false);
                    }
                    else if (jTextField25.getText().equals(empty)){
                        jTextField25.setText(Integer.toString(SB.getIndex(2, 5)));
                        jTextField25.setEditable(false);
                    }
                    else if (jTextField27.getText().equals(empty)){
                        jTextField27.setText(Integer.toString(SB.getIndex(2, 7)));
                        jTextField27.setEditable(false);
                    }
                    else if (jTextField31.getText().equals(empty)){
                        jTextField31.setText(Integer.toString(SB.getIndex(3, 1)));
                        jTextField31.setEditable(false);
                    }
                    else if (jTextField34.getText().equals(empty)){
                        jTextField34.setText(Integer.toString(SB.getIndex(3, 4)));
                        jTextField34.setEditable(false);
                    }
                    else if (jTextField38.getText().equals(empty)){
                        jTextField38.setText(Integer.toString(SB.getIndex(3, 8)));
                        jTextField38.setEditable(false);
                    }
                    else if (jTextField41.getText().equals(empty)){
                        jTextField41.setText(Integer.toString(SB.getIndex(4, 1)));
                        jTextField41.setEditable(false);
                    }
                    else if (jTextField42.getText().equals(empty)){
                        jTextField42.setText(Integer.toString(SB.getIndex(4, 2)));
                        jTextField42.setEditable(false);
                    }
                    else if (jTextField45.getText().equals(empty)){
                        jTextField45.setText(Integer.toString(SB.getIndex(4, 5)));
                        jTextField45.setEditable(false);
                    }
                    else if (jTextField47.getText().equals(empty)){
                        jTextField47.setText(Integer.toString(SB.getIndex(4, 7)));
                        jTextField47.setEditable(false);
                    }
                    else if (jTextField52.getText().equals(empty)){
                        jTextField52.setText(Integer.toString(SB.getIndex(5, 2)));
                        jTextField52.setEditable(false);
                    }
                    else if (jTextField57.getText().equals(empty)){
                        jTextField57.setText(Integer.toString(SB.getIndex(5, 7)));
                        jTextField57.setEditable(false);
                    }
                    else if (jTextField61.getText().equals(empty)){
                        jTextField61.setText(Integer.toString(SB.getIndex(6, 1)));
                        jTextField61.setEditable(false);
                    }
                    else if (jTextField63.getText().equals(empty)){
                        jTextField63.setText(Integer.toString(SB.getIndex(6, 3)));
                        jTextField63.setEditable(false);
                    }
                    else if (jTextField68.getText().equals(empty)){
                        jTextField68.setText(Integer.toString(SB.getIndex(6, 8)));
                        jTextField68.setEditable(false);
                    }
                    else if (jTextField70.getText().equals(empty)){
                        jTextField70.setText(Integer.toString(SB.getIndex(7, 0)));
                        jTextField70.setEditable(false);
                    }
                    else if (jTextField73.getText().equals(empty)){
                        jTextField73.setText(Integer.toString(SB.getIndex(7, 3)));
                        jTextField73.setEditable(false);
                    }
                    else if (jTextField77.getText().equals(empty)){
                        jTextField77.setText(Integer.toString(SB.getIndex(7, 7)));
                        jTextField77.setEditable(false);
                    }
                    else if (jTextField80.getText().equals(empty)){
                        jTextField80.setText(Integer.toString(SB.getIndex(8, 0)));
                        jTextField80.setEditable(false);
                    }
                    else if (jTextField82.getText().equals(empty)){
                        jTextField82.setText(Integer.toString(SB.getIndex(8, 2)));
                        jTextField82.setEditable(false);
                    }
                    else if (jTextField85.getText().equals(empty)){
                        jTextField85.setText(Integer.toString(SB.getIndex(8, 5)));
                        jTextField85.setEditable(false);
                    }
                    else if (jTextField88.getText().equals(empty)){
                        jTextField88.setText(Integer.toString(SB.getIndex(8, 8)));
                        jTextField88.setEditable(false);
                    }
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });
            
            jTextField01.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField01.getText();
                    if (Integer.parseInt(input) == SB.getIndex(0, 1)){
                        jTextField01.setText(input);
                        jTextField01.setEditable(false);
                    }
                    else jTextField01.setText("");
                }});
            jTextField02.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField02.getText();
                    if (Integer.parseInt(input) == SB.getIndex(0, 2)){
                        jTextField02.setText(input);
                        jTextField02.setEditable(false);
                    }
                    else jTextField02.setText("");
                }});
            jTextField04.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField04.getText();
                    if (Integer.parseInt(input) == SB.getIndex(0, 4)){
                        jTextField04.setText(input);
                        jTextField04.setEditable(false);
                    }
                    else jTextField04.setText("");
                }});
            jTextField07.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField07.getText();
                    if (Integer.parseInt(input) == SB.getIndex(0, 7)){
                        jTextField07.setText(input);
                        jTextField07.setEditable(false);
                    }
                    else jTextField07.setText("");
                }});
            jTextField10.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField10.getText();
                    if (Integer.parseInt(input) == SB.getIndex(1, 0)){
                        jTextField10.setText(input);
                        jTextField10.setEditable(false);
                    }
                    else jTextField10.setText("");
                }});
            jTextField12.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField12.getText();
                    if (Integer.parseInt(input) == SB.getIndex(1, 2)){
                        jTextField12.setText(input);
                        jTextField12.setEditable(false);
                    }
                    else jTextField12.setText("");
                }});
            jTextField16.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField16.getText();
                    if (Integer.parseInt(input) == SB.getIndex(1, 6)){
                        jTextField16.setText(input);
                        jTextField16.setEditable(false);
                    }
                    else jTextField16.setText("");
                }});
            jTextField20.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField20.getText();
                    if (Integer.parseInt(input) == SB.getIndex(2, 0)){
                        jTextField20.setText(input);
                        jTextField20.setEditable(false);
                    }
                    else jTextField20.setText("");
                }});
            jTextField23.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField23.getText();
                    if (Integer.parseInt(input) == SB.getIndex(2, 3)){
                        jTextField23.setText(input);
                        jTextField23.setEditable(false);
                    }
                    else jTextField23.setText("");
                }});
            jTextField25.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField25.getText();
                    if (Integer.parseInt(input) == SB.getIndex(2, 5)){
                        jTextField25.setText(input);
                        jTextField25.setEditable(false);
                    }
                    else jTextField25.setText("");
                }});
            jTextField27.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField27.getText();
                    if (Integer.parseInt(input) == SB.getIndex(2, 7)){
                        jTextField27.setText(input);
                        jTextField27.setEditable(false);
                    }
                    else jTextField27.setText("");
                }});
            jTextField31.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField31.getText();
                    if (Integer.parseInt(input) == SB.getIndex(3, 1)){
                        jTextField31.setText(input);
                        jTextField31.setEditable(false);
                    }
                    else jTextField31.setText("");
                }});
            jTextField34.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField34.getText();
                    if (Integer.parseInt(input) == SB.getIndex(3, 4)){
                        jTextField34.setText(input);
                        jTextField34.setEditable(false);
                    }
                    else jTextField34.setText("");
                }});
            jTextField38.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField38.getText();
                    if (Integer.parseInt(input) == SB.getIndex(3, 8)){
                        jTextField38.setText(input);
                        jTextField38.setEditable(false);
                    }
                    else jTextField38.setText("");
                }});
            jTextField41.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField41.getText();
                    if (Integer.parseInt(input) == SB.getIndex(4, 1)){
                        jTextField41.setText(input);
                        jTextField41.setEditable(false);
                    }
                    else jTextField41.setText("");
                }});
            jTextField42.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField42.getText();
                    if (Integer.parseInt(input) == SB.getIndex(4, 2)){
                        jTextField42.setText(input);
                        jTextField42.setEditable(false);
                    }
                    else jTextField42.setText("");
                }});
            jTextField45.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField45.getText();
                    if (Integer.parseInt(input) == SB.getIndex(4, 5)){
                        jTextField45.setText(input);
                        jTextField45.setEditable(false);
                    }
                    else jTextField45.setText("");
                }});
            jTextField47.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField47.getText();
                    if (Integer.parseInt(input) == SB.getIndex(4, 7)){
                        jTextField47.setText(input);
                        jTextField47.setEditable(false);
                    }
                    else jTextField47.setText("");
                }});
            jTextField52.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField52.getText();
                    if (Integer.parseInt(input) == SB.getIndex(5, 2)){
                        jTextField52.setText(input);
                        jTextField52.setEditable(false);
                    }
                    else jTextField52.setText("");
                }});
            jTextField57.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField57.getText();
                    if (Integer.parseInt(input) == SB.getIndex(5, 7)){
                        jTextField57.setText(input);
                        jTextField57.setEditable(false);
                    }
                    else jTextField57.setText("");
                }});
            jTextField61.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField61.getText();
                    if (Integer.parseInt(input) == SB.getIndex(6, 1)){
                        jTextField61.setText(input);
                        jTextField61.setEditable(false);
                    }
                    else jTextField61.setText("");
                }});
            jTextField63.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField63.getText();
                    if (Integer.parseInt(input) == SB.getIndex(6, 3)){
                        jTextField63.setText(input);
                        jTextField63.setEditable(false);
                    }
                    else jTextField63.setText("");
                }});
            jTextField68.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField68.getText();
                    if (Integer.parseInt(input) == SB.getIndex(6, 8)){
                        jTextField68.setText(input);
                        jTextField68.setEditable(false);
                    }
                    else jTextField68.setText("");
                }});
            jTextField70.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField70.getText();
                    if (Integer.parseInt(input) == SB.getIndex(7, 0)){
                        jTextField70.setText(input);
                        jTextField70.setEditable(false);
                    }
                    else jTextField70.setText("");
                }});
            jTextField73.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField73.getText();
                    if (Integer.parseInt(input) == SB.getIndex(7, 3)){
                        jTextField73.setText(input);
                        jTextField73.setEditable(false);
                    }
                    else jTextField73.setText("");
                }});
            jTextField77.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField77.getText();
                    if (Integer.parseInt(input) == SB.getIndex(7, 7)){
                        jTextField77.setText(input);
                        jTextField77.setEditable(false);
                    }
                    else jTextField77.setText("");
                }});
            jTextField80.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField80.getText();
                    if (Integer.parseInt(input) == SB.getIndex(8, 0)){
                        jTextField80.setText(input);
                        jTextField80.setEditable(false);
                    }
                    else jTextField80.setText("");
                }});
            jTextField82.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField82.getText();
                    if (Integer.parseInt(input) == SB.getIndex(8, 2)){
                        jTextField82.setText(input);
                        jTextField82.setEditable(false);
                    }
                    else jTextField82.setText("");
                }});
            jTextField85.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField85.getText();
                    if (Integer.parseInt(input) == SB.getIndex(8, 5)){
                        jTextField85.setText(input);
                        jTextField85.setEditable(false);
                    }
                    else jTextField85.setText("");
                }});
            jTextField88.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String input = jTextField88.getText();
                    if (Integer.parseInt(input) == SB.getIndex(8, 8)){
                        jTextField88.setText(input);
                        jTextField88.setEditable(false);
                    }
                    else jTextField88.setText("");
                }});
        
          //  jTextField80.setText(Integer.toString(SB.getIndex(8, 0)));

    }
    }                                            
//Creates the new board and clears the fields that had already been answered correctly
    public void newBoard()
         {
             SB.nextBoard(0);
             
            jTextField00.setText(Integer.toString(SB.getIndex(0, 0))); jTextField00.setEditable(false);
                    jTextField01.setText(""); jTextField01.setEditable(true);
                    jTextField02.setText(""); jTextField02.setEditable(true);
            jTextField03.setText(Integer.toString(SB.getIndex(0, 3))); jTextField03.setEditable(false);
                    jTextField04.setText(""); jTextField04.setEditable(true);
            jTextField05.setText(Integer.toString(SB.getIndex(0, 5))); jTextField05.setEditable(false);
            jTextField06.setText(Integer.toString(SB.getIndex(0, 6))); jTextField06.setEditable(false);
                    jTextField07.setText(""); jTextField07.setEditable(true);
            jTextField08.setText(Integer.toString(SB.getIndex(0, 8))); jTextField08.setEditable(false);
            
            //other rows
                    jTextField10.setText(""); jTextField10.setEditable(true);
            jTextField11.setText(Integer.toString(SB.getIndex(1, 1))); jTextField11.setEditable(false);
                    jTextField12.setText(""); jTextField12.setEditable(true);
            jTextField13.setText(Integer.toString(SB.getIndex(1, 3))); jTextField13.setEditable(false);
            jTextField14.setText(Integer.toString(SB.getIndex(1, 4))); jTextField14.setEditable(false);
            jTextField15.setText(Integer.toString(SB.getIndex(1, 5))); jTextField15.setEditable(false);
                    jTextField16.setText(""); jTextField16.setEditable(true);
            jTextField17.setText(Integer.toString(SB.getIndex(1, 7))); jTextField17.setEditable(false);
            jTextField18.setText(Integer.toString(SB.getIndex(1, 8))); jTextField18.setEditable(false);
            
                    jTextField20.setText(""); jTextField20.setEditable(true);
            jTextField21.setText(Integer.toString(SB.getIndex(2, 1))); jTextField21.setEditable(false);
            jTextField22.setText(Integer.toString(SB.getIndex(2, 2))); jTextField22.setEditable(false);
                    jTextField23.setText(""); jTextField23.setEditable(true);
            jTextField24.setText(Integer.toString(SB.getIndex(2, 4))); jTextField24.setEditable(false);
                    jTextField25.setText(""); jTextField25.setEditable(true);
            jTextField26.setText(Integer.toString(SB.getIndex(2, 6))); jTextField26.setEditable(false);
                    jTextField27.setText(""); jTextField27.setEditable(true);
            jTextField28.setText(Integer.toString(SB.getIndex(2, 8))); jTextField28.setEditable(false);
            
            jTextField30.setText(Integer.toString(SB.getIndex(3, 0))); jTextField30.setEditable(false);
                    jTextField31.setText(""); jTextField31.setEditable(true);
            jTextField32.setText(Integer.toString(SB.getIndex(3, 2))); jTextField32.setEditable(false);
            jTextField33.setText(Integer.toString(SB.getIndex(3, 3))); jTextField33.setEditable(false);
                    jTextField34.setText(""); jTextField34.setEditable(true);
            jTextField35.setText(Integer.toString(SB.getIndex(3, 5))); jTextField35.setEditable(false);
            jTextField36.setText(Integer.toString(SB.getIndex(3, 6))); jTextField36.setEditable(false);
            jTextField37.setText(Integer.toString(SB.getIndex(3, 7))); jTextField37.setEditable(false);
                    jTextField38.setText(""); jTextField38.setEditable(true);
            
            jTextField40.setText(Integer.toString(SB.getIndex(4, 0))); jTextField40.setEditable(false);
                    jTextField41.setText(""); jTextField41.setEditable(true);
                    jTextField42.setText(""); jTextField42.setEditable(true);
            jTextField43.setText(Integer.toString(SB.getIndex(4, 3))); jTextField43.setEditable(false);
            jTextField44.setText(Integer.toString(SB.getIndex(4, 4))); jTextField44.setEditable(false);
                    jTextField45.setText(""); jTextField45.setEditable(true);
            jTextField46.setText(Integer.toString(SB.getIndex(4, 6))); jTextField46.setEditable(false);
                    jTextField47.setText(""); jTextField47.setEditable(true);
            jTextField48.setText(Integer.toString(SB.getIndex(4, 8))); jTextField48.setEditable(false);
            
            jTextField50.setText(Integer.toString(SB.getIndex(5, 0))); jTextField50.setEditable(false);
            jTextField51.setText(Integer.toString(SB.getIndex(5, 1))); jTextField51.setEditable(false);
                    jTextField52.setText(""); jTextField52.setEditable(true);
            jTextField53.setText(Integer.toString(SB.getIndex(5, 3))); jTextField53.setEditable(false);
            jTextField54.setText(Integer.toString(SB.getIndex(5, 4))); jTextField54.setEditable(false);
            jTextField55.setText(Integer.toString(SB.getIndex(5, 5))); jTextField55.setEditable(false);
            jTextField56.setText(Integer.toString(SB.getIndex(5, 6))); jTextField56.setEditable(false);
                    jTextField57.setText(""); jTextField57.setEditable(true);
            jTextField58.setText(Integer.toString(SB.getIndex(5, 8))); jTextField58.setEditable(false);
            
            jTextField60.setText(Integer.toString(SB.getIndex(6, 0))); jTextField60.setEditable(false);
                    jTextField61.setText(""); jTextField61.setEditable(true);
            jTextField62.setText(Integer.toString(SB.getIndex(6, 2))); jTextField62.setEditable(false);
                    jTextField63.setText(""); jTextField63.setEditable(true);
            jTextField64.setText(Integer.toString(SB.getIndex(6, 4))); jTextField64.setEditable(false);
            jTextField65.setText(Integer.toString(SB.getIndex(6, 5))); jTextField65.setEditable(false);
            jTextField66.setText(Integer.toString(SB.getIndex(6, 6))); jTextField66.setEditable(false);
            jTextField67.setText(Integer.toString(SB.getIndex(6, 7))); jTextField67.setEditable(false);
                    jTextField68.setText(""); jTextField68.setEditable(true);
            
                    jTextField70.setText(""); jTextField70.setEditable(true);
            jTextField71.setText(Integer.toString(SB.getIndex(7, 1))); jTextField71.setEditable(false);
            jTextField72.setText(Integer.toString(SB.getIndex(7, 2))); jTextField72.setEditable(false);
                    jTextField73.setText(""); jTextField73.setEditable(true);
            jTextField74.setText(Integer.toString(SB.getIndex(7, 4))); jTextField74.setEditable(false);
            jTextField75.setText(Integer.toString(SB.getIndex(7, 5))); jTextField75.setEditable(false);
            jTextField76.setText(Integer.toString(SB.getIndex(7, 6))); jTextField76.setEditable(false);
                    jTextField77.setText(""); jTextField77.setEditable(true);
            jTextField78.setText(Integer.toString(SB.getIndex(7, 8))); jTextField78.setEditable(false);
            
                    jTextField80.setText(""); jTextField80.setEditable(true);
            jTextField81.setText(Integer.toString(SB.getIndex(8, 1))); jTextField81.setEditable(false);
                    jTextField82.setText(""); jTextField82.setEditable(true);
            jTextField83.setText(Integer.toString(SB.getIndex(8, 3))); jTextField83.setEditable(false);
            jTextField84.setText(Integer.toString(SB.getIndex(8, 4))); jTextField84.setEditable(false);
                    jTextField85.setText(""); jTextField85.setEditable(true);
            jTextField86.setText(Integer.toString(SB.getIndex(8, 6))); jTextField86.setEditable(false);
            jTextField87.setText(Integer.toString(SB.getIndex(8, 7))); jTextField87.setEditable(false);
                    jTextField88.setText(""); jTextField88.setEditable(true);
         }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sudokuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sudokuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sudokuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sudokuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sudokuTest().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonBad;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField00;
    private javax.swing.JTextField jTextField01;
    private javax.swing.JTextField jTextField02;
    private javax.swing.JTextField jTextField03;
    private javax.swing.JTextField jTextField04;
    private javax.swing.JTextField jTextField05;
    private javax.swing.JTextField jTextField06;
    private javax.swing.JTextField jTextField07;
    private javax.swing.JTextField jTextField08;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    // End of variables declaration                   
}
